// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwubknduipwlnvmkdril.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3dWJrbmR1aXB3bG52bWtkcmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTU4ODAsImV4cCI6MjA2NzY3MTg4MH0.nUV0FvPO3q0N99MBX0BdZA70KmWLzbFj5toc8b6794M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});